version: '3.4'

services:
  mynewapi:
    image: ${DOCKER_REGISTRY-}mynewapi
    build:
      context: .
      dockerfile: MyNewApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  mynewapi.database:
    image: postgres:latest
    environment:
        - POSTGRES_DB=products
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./.containers/prodycts-db:/var/lib/posgresql/data
    ports:
     - "5432:5432"